version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}  # Set the secret key base here
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
      SSL_CERTIFICATE: ${SSL_CERTIFICATE}
      SSL_CERTIFICATE_KEY: ${SSL_CERTIFICATE_KEY}
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/app  # Mount your application code for static files
      - ./config/certs:/etc/nginx/ssl  # Mount the SSL certificate and key
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    depends_on:
      - web
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
